# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\";\n\x13\x41uthenticateRequest\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\x05\"3\n\x11\x41uthenticateReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0e\n\x06secret\x18\x02 \x01(\x0c\"^\n\x11\x43reateUserRequest\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\x05\x12\x13\n\x0bpermissions\x18\x03 \x01(\t\x12\x0e\n\x06secret\x18\x04 \x01(\x0c\"!\n\x0f\x43reateUserReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\"%\n\x13VerifyAccessRequest\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\"(\n\x11VerifyAccessReply\x12\x13\n\x0bpermissions\x18\x01 \x01(\t\"\x18\n\x16\x46inishExecutionRequest\"%\n\x14\x46inishExecutionReply\x12\r\n\x05users\x18\x01 \x01(\x05\x32\xa1\x02\n\x04\x41uth\x12\x44\n\x0c\x41uthenticate\x12\x19.auth.AuthenticateRequest\x1a\x17.auth.AuthenticateReply\"\x00\x12>\n\nCreateUser\x12\x17.auth.CreateUserRequest\x1a\x15.auth.CreateUserReply\"\x00\x12\x44\n\x0cVerifyAccess\x12\x19.auth.VerifyAccessRequest\x1a\x17.auth.VerifyAccessReply\"\x00\x12M\n\x0f\x46inishExecution\x12\x1c.auth.FinishExecutionRequest\x1a\x1a.auth.FinishExecutionReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHENTICATEREQUEST._serialized_start=20
  _AUTHENTICATEREQUEST._serialized_end=79
  _AUTHENTICATEREPLY._serialized_start=81
  _AUTHENTICATEREPLY._serialized_end=132
  _CREATEUSERREQUEST._serialized_start=134
  _CREATEUSERREQUEST._serialized_end=228
  _CREATEUSERREPLY._serialized_start=230
  _CREATEUSERREPLY._serialized_end=263
  _VERIFYACCESSREQUEST._serialized_start=265
  _VERIFYACCESSREQUEST._serialized_end=302
  _VERIFYACCESSREPLY._serialized_start=304
  _VERIFYACCESSREPLY._serialized_end=344
  _FINISHEXECUTIONREQUEST._serialized_start=346
  _FINISHEXECUTIONREQUEST._serialized_end=370
  _FINISHEXECUTIONREPLY._serialized_start=372
  _FINISHEXECUTIONREPLY._serialized_end=409
  _AUTH._serialized_start=412
  _AUTH._serialized_end=701
# @@protoc_insertion_point(module_scope)
